---
#
# EECS 4287/5287: Principles of Cloud Computing
# Author: Aniruddha Gokhale
# Created: Fall 2017
# Modified: Fall 2020
#
# This playbook is our demo master file
# The goal is to show how to have a single master file which then
# includes multiple plays according to some well-designed choreography
#
# This file is similar to the one in the AnsibleOnly_Local_and_Cloud folder
# For now I just kept one play in here but feel free to add more.
#####################################################
### Play 1: Get facts from all our VMs
#
# Here I show the use of import_tasks from child playbooks
#####################################################
#- name: "Setup Local"
#  hosts: MyLocalVMs          # specified in the MyInventory file
#  remote_user:  ubuntu      # note that the user is ubuntu for 
#                             # vagrant-created VM else use the
#                             # appropriate user name
#
#  gather_facts: yes          # We ask Ansible to collect all facts
#  become_user: no            # No need for sudo as we are not installing anything#
#
#  tasks:    # the task to be performed (here I am showing the effect of include_)
 # - include_tasks: createChameleon.yml

#  - include_tasks: setupLocal.yml

 #
 
# PLAY 2
#- name: "Setup VM 2"
#  hosts: VM2
#  remote_user: cc
#  gather_facts: yes   
#  become: yes       
 # become_user: cc
 # tasks:
 #   - include_tasks: setupVM2.yml

# PLAY 3
#- name: "Setup VM 3"
#  collections:   
#    - openstack.cloud
#  hosts: VM3
#  remote_user: cc
#  gather_facts: yes
#  become: yes          
#  become_user: cc 
#  tasks:
#    - include_tasks: setupVM3.yml

# PLAY 4    
- name: "Run Consumer"
  hosts: VM3
  remote_user: cc
  gather_facts: yes          
  become_user: no  
  tasks:
  - include_tasks: runConsumer.yml

# PLAY 4    
- name: "Run Producer"
  hosts: MyLocalVMs
  remote_user:  ubuntu
  gather_facts: yes          
  become_user: no  
  tasks:
  - include_tasks: runProducer.yml

...
