---

  - name: Test File
    openstack.cloud.server_info:
        cloud: CH-822922   # this is the nickname from our clouds.yaml file
        server: cpyvm2     # set this whatever you are interested in
    register: result            # this is a way to store output in a variable

  - name: "Print results"
    
... 